name: Deply to aws

on: workflow_dispatch

jobs:
    deplay:
        runs-on: self-hosted
        environment: DEV
    
        steps:
            - name: Install nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 23

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install
              env:
                PORT: ${{ vars.PORT }}

            - name: Start server
              run: pm2 restart server
              
